[2024-12-31T10:40:11.778+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-31T10:40:11.824+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: de01-final-project-dag.load-and-clean manual__2024-12-31T10:35:26.025356+00:00 [queued]>
[2024-12-31T10:40:11.846+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: de01-final-project-dag.load-and-clean manual__2024-12-31T10:35:26.025356+00:00 [queued]>
[2024-12-31T10:40:11.848+0000] {taskinstance.py:2866} INFO - Starting attempt 5 of 11
[2024-12-31T10:40:11.890+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load-and-clean> on 2024-12-31 10:35:26.025356+00:00
[2024-12-31T10:40:11.913+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=282) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-31T10:40:11.916+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'de01-final-project-dag', 'load-and-clean', 'manual__2024-12-31T10:35:26.025356+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpzwodbe0n']
[2024-12-31T10:40:11.918+0000] {standard_task_runner.py:72} INFO - Started process 298 to run task
[2024-12-31T10:40:11.919+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask load-and-clean
[2024-12-31T10:40:12.491+0000] {task_command.py:467} INFO - Running <TaskInstance: de01-final-project-dag.load-and-clean manual__2024-12-31T10:35:26.025356+00:00 [running]> on host 864534f4bb16
[2024-12-31T10:40:12.688+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='de01-final-project-dag' AIRFLOW_CTX_TASK_ID='load-and-clean' AIRFLOW_CTX_EXECUTION_DATE='2024-12-31T10:35:26.025356+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-31T10:35:26.025356+00:00'
[2024-12-31T10:40:12.691+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-31T10:40:12.693+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-31T10:40:12.695+0000] {logging_mixin.py:190} INFO - Current task name:load-and-clean state:running start_date:2024-12-31 10:40:11.825987+00:00
[2024-12-31T10:40:12.696+0000] {logging_mixin.py:190} INFO - Dag name:de01-final-project-dag and current dag run status:running
[2024-12-31T10:40:12.697+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-31T10:40:12.755+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dags.py", line 36, in load_and_clean
    raise Exception(f'Script failed with error: {result.stderr}')
Exception: Script failed with error: python: can't open file '/opt/***/nyc-collisions-download-cleanup.py': [Errno 2] No such file or directory

[2024-12-31T10:40:12.795+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-31T10:40:12.797+0000] {logging_mixin.py:190} INFO - Task start:2024-12-31 10:40:11.825987+00:00 end:2024-12-31 10:40:12.794239+00:00 duration:0.968252
[2024-12-31T10:40:12.798+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load-and-clean> dag:<DAG: de01-final-project-dag> dagrun:<DagRun de01-final-project-dag @ 2024-12-31 10:35:26.025356+00:00: manual__2024-12-31T10:35:26.025356+00:00, state:running, queued_at: 2024-12-31 10:35:26.087033+00:00. externally triggered: True>
[2024-12-31T10:40:12.799+0000] {logging_mixin.py:190} INFO - Failure caused by Script failed with error: python: can't open file '/opt/***/nyc-collisions-download-cleanup.py': [Errno 2] No such file or directory
[2024-12-31T10:40:12.801+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=de01-final-project-dag, task_id=load-and-clean, run_id=manual__2024-12-31T10:35:26.025356+00:00, execution_date=20241231T103526, start_date=20241231T104011, end_date=20241231T104012
[2024-12-31T10:40:12.846+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-31T10:40:12.847+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 28 for task load-and-clean (Script failed with error: python: can't open file '/opt/***/nyc-collisions-download-cleanup.py': [Errno 2] No such file or directory
; 298)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dags.py", line 36, in load_and_clean
    raise Exception(f'Script failed with error: {result.stderr}')
Exception: Script failed with error: python: can't open file '/opt/***/nyc-collisions-download-cleanup.py': [Errno 2] No such file or directory

[2024-12-31T10:40:12.907+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-31T10:40:13.304+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-31T10:40:13.314+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
